name: Build Project

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'  # 当推送标签如 v1.0.0 时触发
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libtbb-dev

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: ./build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        working-directory: ./build
        run: make -j $(nproc)
        
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/MeshConverter
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: ./build
        run: cmake .. -G "Visual Studio 17 2022" -A x64

      - name: Build project (Debug)
        working-directory: ./build
        run: msbuild MeshConverter.sln /p:Configuration=Debug /p:Platform=x64

      - name: Build project (Release)
        working-directory: ./build
        run: msbuild MeshConverter.sln /p:Configuration=Release /p:Platform=x64
        
      - name: Upload Windows Debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug-build
          path: build/Debug/MeshConverter.exe
          retention-days: 7
          
      - name: Upload Windows Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-build
          path: build/Release/MeshConverter.exe
          retention-days: 7

  create-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    # 只有在推送标签时才创建发布版本
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release package
        run: |
          mkdir -p release-package
          cp artifacts/linux-build/MeshConverter release-package/MeshConverter-linux
          cp artifacts/windows-debug-build/MeshConverter.exe release-package/MeshConverter-windows-debug.exe
          cp artifacts/windows-release-build/MeshConverter.exe release-package/MeshConverter-windows-release.exe
          cd release-package && zip -r ../MeshConverter.zip *

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: MeshConverter.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 每次推送到 master 分支也创建一个最新版本的构建
  create-latest-build:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create latest package
        run: |
          mkdir -p latest-build
          cp artifacts/linux-build/MeshConverter latest-build/MeshConverter-linux
          cp artifacts/windows-debug-build/MeshConverter.exe latest-build/MeshConverter-windows-debug.exe
          cp artifacts/windows-release-build/MeshConverter.exe latest-build/MeshConverter-windows-release.exe
          cd latest-build && zip -r ../MeshConverter-latest.zip *

      - name: Upload latest build
        uses: actions/upload-artifact@v4
        with:
          name: MeshConverter-latest
          path: MeshConverter-latest.zip
          retention-days: 30
